"""
SearXNG AI Summary Plugin
=========================
Generates an AI-powered summary at the top of search results,
similar to Google's AI Overview and DuckDuckGo's Search Assist.

Connects to any OpenAI-compatible endpoint (OpenAI, Ollama, LM Studio,
LocalAI, vLLM, Groq, Together AI, etc.)

ALL configuration lives in settings.yml under the plugin's key.
Do not edit this file to change settings — edit settings.yml instead.

    plugins:
      searx.plugins.ai_summary.SXNGPlugin:
        active: true
        base_url: "http://localhost:11434/v1"
        api_key: "ollama"
        model: "llama3"
        max_results: 5
        max_tokens: 300
        timeout: 20
        system_prompt: >
          You are a helpful assistant embedded in a search engine. ...

Installation: see README.md
"""

import httpx
import json
import logging
from typing import TYPE_CHECKING, Optional

from flask_babel import gettext
from searx.plugins import Plugin, PluginCfg, PluginInfo
from searx.result_types import EngineResults, Answer

if TYPE_CHECKING:
    from searx.extended_types import SXNG_Request
    from searx.search import SearchWithPlugins

logger = logging.getLogger(__name__)

_DEFAULT_SYSTEM_PROMPT = (
    "You are a helpful assistant embedded in a search engine. "
    "The user searched for a query and you are given the top search results. "
    "Write a concise, factual summary (3-5 sentences) that directly answers "
    "the query using the provided results. "
    "Do NOT start with 'Based on the results' or similar meta-phrases. "
    "Do NOT include markdown formatting. "
    "If the results are unrelated to the query, say you could not find a clear answer."
)


class SXNGPlugin(Plugin):
    """AI-powered summary box above search results (OpenAI-compatible endpoint)."""

    # ── Required plugin identity ──────────────────────────────────────────────
    id = "ai_summary"

    # ── Run on every query (no keyword trigger needed) ────────────────────────
    keywords: list = []

    def __init__(self, plg_cfg: PluginCfg) -> None:
        super().__init__(plg_cfg)

        self.info = PluginInfo(
            id=self.id,
            name=gettext("AI Summary"),
            description=gettext("Show an AI-generated summary above search results"),
            preference_section="general",
        )

        # ── Settings injected from settings.yml via PluginCfg ────────────────
        # All values below are set as instance attributes by Plugin.__init__
        # when it iterates plg_cfg.__dict__.  Provide safe defaults here in
        # case an optional key is omitted from settings.yml.

        # Required — log a clear error if missing
        for required in ("base_url", "api_key", "model"):
            if not getattr(self, required, None):
                raise ValueError(
                    f"[ai_summary] 'plugins.searx.plugins.ai_summary.SXNGPlugin.{required}' "
                    f"is missing or blank in settings.yml."
                )

        # Optional with safe defaults
        if not getattr(self, "system_prompt", None):
            self.system_prompt = _DEFAULT_SYSTEM_PROMPT
        if not getattr(self, "max_results", None):
            self.max_results = 5
        if not getattr(self, "max_tokens", None):
            self.max_tokens = 300
        if not getattr(self, "timeout", None):
            self.timeout = 20

        # Ensure correct types for numeric settings
        self.max_results = int(self.max_results)
        self.max_tokens  = int(self.max_tokens)
        self.timeout     = float(self.timeout)

    # ── Helpers ───────────────────────────────────────────────────────────────

    def _build_user_prompt(self, query: str, results: list) -> str:
        lines = [f'Search query: "{query}"\n', "Top search results:\n"]
        for i, result in enumerate(results, 1):
            title   = result.get("title", "")
            content = result.get("content", "")
            url     = result.get("url", "")
            lines.append(f"{i}. [{title}] ({url})\n   {content}\n")
        lines.append("\nPlease write a concise summary that answers the search query.")
        return "\n".join(lines)

    def _call_llm(self, query: str, results: list) -> Optional[str]:
        base_url = self.base_url.rstrip("/")
        endpoint = f"{base_url}/chat/completions"
        headers  = {
            "Content-Type":  "application/json",
            "Authorization": f"Bearer {self.api_key}",
        }
        payload = {
            "model":       self.model,
            "max_tokens":  self.max_tokens,
            "temperature": 0.3,
            "messages": [
                {"role": "system", "content": self.system_prompt},
                {"role": "user",   "content": self._build_user_prompt(query, results)},
            ],
        }

        try:
            resp = httpx.post(endpoint, headers=headers, json=payload, timeout=self.timeout)
            resp.raise_for_status()
            data = resp.json()
            return data["choices"][0]["message"]["content"].strip()

        except httpx.TimeoutException:
            logger.warning(
                "ai_summary: request timed out (%ss) — increase timeout in settings.yml",
                self.timeout,
            )
        except httpx.HTTPStatusError as exc:
            logger.warning(
                "ai_summary: HTTP %s from %s — check base_url / api_key in settings.yml",
                exc.response.status_code, endpoint,
            )
        except (KeyError, IndexError, json.JSONDecodeError) as exc:
            logger.warning("ai_summary: unexpected LLM response format: %s", exc)
        except Exception as exc:  # pylint: disable=broad-except
            logger.warning("ai_summary: unexpected error: %s", exc)

        return None

    # ── SearXNG hook ──────────────────────────────────────────────────────────

    def post_search(
        self,
        request: "SXNG_Request",
        search:  "SearchWithPlugins",
    ) -> EngineResults:
        results = EngineResults()

        # Only run on page 1
        if search.search_query.pageno > 1:
            return results

        # Gather text-bearing results only
        text_results = [
            r for r in search.result_container.get_ordered_results()
            if r.get("content")
        ]
        if not text_results:
            return results

        query   = search.search_query.query
        summary = self._call_llm(query, text_results[: self.max_results])

        if summary:
            # Answer results appear in the highlighted box above search results
            results.answers.add(
                Answer(
                    answer=summary,
                    # The template macro checks for this key to apply custom styling
                    url=None,
                )
            )

        return results